[supervisord]
nodaemon=true

[program:uvicorn]
command=uvicorn app_fast:app --host 0.0.0.0 --port 5500 --reload
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:celery]
command=celery -A celery_app.celery_app worker --loglevel=info
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
