# -*- coding: utf-8 -*-
"""Creating informatio pool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8M_gUlPBXSPApxmH0Zbkf0Xbx5QyKVR
"""

!pip install tavily-python

import os
import re
import json
import hashlib
from datetime import datetime
from typing import Any, Dict, List
from urllib.parse import urlparse

from dotenv import load_dotenv
from openai import OpenAI
from tavily import TavilyClient


load_dotenv()

os.environ["OPENAI_API_KEY"] = getpass("OpenAI API key: ")
os.environ["TAVILY_API_KEY"] = getpass("Tavily API key: ")

openai_client = OpenAI()
tavily_client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])

# ---------------------------------------------------------
# OpenAI JSON helper
# ---------------------------------------------------------

def ask_openai_json(
    prompt: str,
    model: str = "gpt-5.4-mini",
    temperature: float = 0.2,
    max_retries: int = 3
) -> Any:

    last_error = None
    last_content = None

    for attempt in range(1, max_retries + 1):
        response = openai_client.chat.completions.create(
            model=model,
            temperature=temperature,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a careful research assistant. "
                        "Return valid JSON only. No markdown. "
                        "Do not include explanations outside JSON."
                    )
                },
                {"role": "user", "content": prompt}
            ]
        )

        content = response.choices[0].message.content
        last_content = content

        try:
            return json.loads(content)

        except json.JSONDecodeError as e:
            last_error = e
            print(f"Attempt {attempt} failed: Invalid JSON")

            # Try extracting JSON from messy output
            try:
                match = re.search(r"\{.*\}|\[.*\]", content, re.DOTALL)
                if match:
                    return json.loads(match.group(0))
            except json.JSONDecodeError as e2:
                last_error = e2

    raise ValueError(
        f"OpenAI failed to return valid JSON after {max_retries} attempts.\n\n"
        f"Last JSON error: {last_error}\n\n"
        f"Last content:\n{last_content}"
    )

# ---------------------------------------------------------
# Source quality
# ---------------------------------------------------------

def get_domain(url: str) -> str:
    return urlparse(url).netloc.lower().replace("www.", "")


def source_quality_tier(url: str) -> int:
    """
    Lower is better.

    1 = peer-reviewed / preprint / technical academic
    2 = institutional
    3 = strong technical company source
    4 = general source
    5 = weak / commentary / marketing
    """

    domain = get_domain(url)

    tier_1 = [
        "arxiv.org",
        "springer.com",
        "nature.com",
        "science.org",
        "acm.org",
        "ieee.org",
        "sciencedirect.com",
        "iopscience.iop.org",
        "jmlr.org",
    ]

    tier_2 = [
        ".edu",
        ".gov",
        "who.int",
        "oecd.org",
        "unesco.org",
    ]

    tier_3 = [
        "nvidia.com",
        "developer.nvidia.com",
        "research.google",
        "ai.googleblog.com",
        "ai.meta.com",
        "openai.com",
        "microsoft.com/en-us/research",
        "deepmind.google",
    ]

    tier_5 = [
        "slideshare.net",
        "scribd.com",
        "linkedin.com",
        "medium.com",
        "prnewswire.com",
        "businesswire.com",
        "substack.com",
    ]

    if any(d in domain for d in tier_1):
        return 1

    if any(d in domain for d in tier_2):
        return 2

    if any(d in domain for d in tier_3):
        return 3

    if any(d in domain for d in tier_5):
        return 5

    return 4


def source_weight(tier: int) -> float:
    weights = {
        1: 3.0,
        2: 2.0,
        3: 1.2,
        4: 0.7,
        5: 0.2,
    }
    return weights.get(tier, 0.5)


# ---------------------------------------------------------
# Deduplication
# ---------------------------------------------------------

def content_hash(text: str, length: int = 2000) -> str:
    clean = re.sub(r"\s+", " ", text or "").strip().lower()
    clean = clean[:length]
    return hashlib.sha256(clean.encode("utf-8")).hexdigest()


def dedupe_sources(sources: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Deduplicate by:
    - same domain
    - near-identical beginning content hash

    This prevents duplicated SlideShare / mirrored pages
    from being counted as independent corroboration.
    """

    seen_domains = set()
    seen_hashes = set()
    deduped = []

    for source in sources:
        url = source.get("url", "")
        raw_content = source.get("raw_content", "")

        domain = get_domain(url)
        h = content_hash(raw_content)

        if domain in seen_domains:
            continue

        if h in seen_hashes:
            continue

        seen_domains.add(domain)
        seen_hashes.add(h)

        deduped.append(source)

    return deduped


# ---------------------------------------------------------
# Subtopic generation
# ---------------------------------------------------------

def generate_subtopics(topic: str, min_subtopics: int = 4, max_subtopics: int = 10) -> List[str]:
    prompt = f"""
Break this topic into {min_subtopics} to {max_subtopics} important subtopics.

Topic:
{topic}

Rules:
- Subtopics must be useful for a canonical educational document.
- Avoid overlap.
- Keep subtopics short.
- Return JSON array only.
"""

    result = ask_openai_json(prompt)

    if not isinstance(result, list):
        raise ValueError("Subtopics must be a list.")

    return [str(x).strip() for x in result if str(x).strip()][:max_subtopics]


# ---------------------------------------------------------
# Tavily search with source filtering
# ---------------------------------------------------------

def tavily_search_quality_sources(
    topic: str,
    subtopic: str,
    max_results: int = 10,
    max_tier: int = 3
) -> List[Dict[str, Any]]:

    query = f"{topic} {subtopic} explanation research technical source"

    response = tavily_client.search(
        query=query,
        search_depth="advanced",
        max_results=max_results,
        include_answer=False,
        include_raw_content=True
    )

    sources = []

    for item in response.get("results", []):
        url = item.get("url")
        raw_content = item.get("raw_content") or item.get("content") or ""

        if not url or not raw_content:
            continue

        tier = source_quality_tier(url)

        if tier > max_tier:
            continue

        sources.append({
            "title": item.get("title"),
            "url": url,
            "domain": get_domain(url),
            "tavily_score": item.get("score"),
            "source_quality_tier": tier,
            "source_weight": source_weight(tier),
            "raw_content": raw_content[:12000],
        })

    return dedupe_sources(sources)


# ---------------------------------------------------------
# Fallback search if source quality is poor
# ---------------------------------------------------------

def search_with_fallback(
    topic: str,
    subtopic: str,
    min_sources: int = 3
) -> List[Dict[str, Any]]:

    sources = tavily_search_quality_sources(
        topic=topic,
        subtopic=subtopic,
        max_results=10,
        max_tier=3
    )

    if len(sources) >= min_sources:
        return sources

    refined_queries = [
        f"{topic} {subtopic} site:arxiv.org OR site:ieee.org OR site:acm.org",
        f"{topic} {subtopic} research paper",
        f"{topic} {subtopic} university explanation",
    ]

    for query in refined_queries:
        response = tavily_client.search(
            query=query,
            search_depth="advanced",
            max_results=10,
            include_answer=False,
            include_raw_content=True
        )

        for item in response.get("results", []):
            url = item.get("url")
            raw_content = item.get("raw_content") or item.get("content") or ""

            if not url or not raw_content:
                continue

            tier = source_quality_tier(url)

            if tier <= 3:
                sources.append({
                    "title": item.get("title"),
                    "url": url,
                    "domain": get_domain(url),
                    "tavily_score": item.get("score"),
                    "source_quality_tier": tier,
                    "source_weight": source_weight(tier),
                    "raw_content": raw_content[:12000],
                })

        sources = dedupe_sources(sources)

        if len(sources) >= min_sources:
            break

    return sources


# ---------------------------------------------------------
# Extract atomic claims with source quotes
# ---------------------------------------------------------

def extract_claims_from_sources(
    topic: str,
    subtopic: str,
    sources: List[Dict[str, Any]]
) -> Dict[str, Any]:

    source_text = ""

    for i, source in enumerate(sources, start=1):
        source_id = f"S{i}"
        source["source_id"] = source_id

        source_text += f"""
SOURCE_ID: {source_id}
TITLE: {source["title"]}
URL: {source["url"]}
QUALITY_TIER: {source["source_quality_tier"]}
CONTENT:
{source["raw_content"]}
---
"""

    prompt = f"""
Topic:
{topic}

Subtopic:
{subtopic}

You are given raw source content.

Task:
Extract important factual claims.

Rules:
- Extract atomic claims only.
- One claim = one idea.
- Ignore ads, navigation, cookie text, author bios, and marketing fluff.
- Each claim must include a short verbatim quote from the source that supports it.
- Do not invent claims.
- Prefer technical, educational, and definitional information.
- Avoid vague claims like "X is revolutionary" or "X will transform the future" unless the source provides concrete evidence.

Sources:
{source_text}

Return JSON only:

{{
  "subtopic": "{subtopic}",
  "claims": [
    {{
      "claim": "Atomic factual claim.",
      "source_id": "S1",
      "source_url": "https://example.com",
      "source_quality_tier": 1,
      "source_weight": 3.0,
      "source_quote": "Short exact quote supporting the claim."
    }}
  ]
}}
"""

    return ask_openai_json(prompt)


# ---------------------------------------------------------
# Cluster claims using OpenAI, but with strict anti-overmerge rule
# ---------------------------------------------------------

def cluster_claims_strict(all_claims: List[Dict[str, Any]]) -> Dict[str, Any]:
    prompt = f"""
You are clustering extracted claims.

Task:
Group claims only if they express the SAME factual idea.

Important:
- Do NOT merge claims just because they are related.
- Search, optimization, sampling, coordination, and game theory are different claims unless the wording says the same thing.
- Preserve specificity.
- It is better to create more small clusters than fewer broad clusters.

Input:
{json.dumps(all_claims, indent=2)}

Return JSON only:

{{
  "claim_clusters": [
    {{
      "canonical_claim": "Most precise version of the shared claim.",
      "claims": [
        {{
          "claim": "Original claim",
          "source_url": "https://example.com",
          "source_quality_tier": 1,
          "source_weight": 3.0,
          "source_quote": "Quote"
        }}
      ]
    }}
  ]
}}
"""

    return ask_openai_json(prompt)


# ---------------------------------------------------------
# Weighted verification
# ---------------------------------------------------------

def verify_clusters_weighted(claim_clusters: Dict[str, Any]) -> Dict[str, Any]:
    verified = []

    for cluster in claim_clusters.get("claim_clusters", []):
        claims = cluster.get("claims", [])

        unique_domains = set()
        unique_urls = set()
        weighted_score = 0.0
        best_tier = 5
        quotes = []

        for claim in claims:
            url = claim.get("source_url", "")
            domain = get_domain(url)

            if domain in unique_domains:
                continue

            unique_domains.add(domain)
            unique_urls.add(url)

            tier = int(claim.get("source_quality_tier", 5))
            weight = float(claim.get("source_weight", source_weight(tier)))

            weighted_score += weight
            best_tier = min(best_tier, tier)

            quotes.append({
                "source_url": url,
                "source_quality_tier": tier,
                "source_quote": claim.get("source_quote", "")
            })

        if weighted_score >= 5.0 and best_tier <= 2:
            trust_label = "high"
        elif weighted_score >= 3.0:
            trust_label = "medium"
        elif weighted_score >= 1.0:
            trust_label = "low"
        else:
            trust_label = "unverified"

        verified.append({
            "canonical_claim": cluster.get("canonical_claim"),
            "trust_label": trust_label,
            "weighted_support_score": round(weighted_score, 2),
            "unique_source_count": len(unique_urls),
            "supporting_source_urls": list(unique_urls),
            "supporting_quotes": quotes,
        })

    return {"verified_claims": verified}


# ---------------------------------------------------------
# Stronger writer
# ---------------------------------------------------------

def write_canonical_document(
    topic: str,
    subtopics: List[str],
    verified_claims: Dict[str, Any],
    model: str = "gpt-4.1"
) -> Dict[str, Any]:

    prompt = f"""
You are writing a canonical educational document.

Topic:
{topic}

Subtopics:
{json.dumps(subtopics, indent=2)}

Verified claims:
{json.dumps(verified_claims, indent=2)}

Rules:
- Use only high and medium trust claims in canonical_text.
- Do NOT state low-trust claims as fact in prose.
- Low-trust claims may appear only in a separate "low_trust_notes" field.
- Do not include unverified claims.
- Every key point must include trust_label and sources.
- Keep the text clean, neutral, and educational.
- Avoid hype, marketing language, and unsupported future predictions.
- If evidence is weak, say the evidence is weak.

Return JSON only:

{{
  "topic": "{topic}",
  "canonical_summary": "Brief summary using only medium/high trust claims.",
  "sections": [
    {{
      "subtopic": "Subtopic name",
      "canonical_text": "Explanation using only high/medium trust claims.",
      "key_points": [
        {{
          "point": "Supported point.",
          "trust_label": "high",
          "sources": ["https://source.com"]
        }}
      ],
      "low_trust_notes": [
        {{
          "point": "Some sources suggest...",
          "sources": ["https://source.com"]
        }}
      ]
    }}
  ],
  "source_index": [
    {{
      "url": "https://source.com",
      "claims_supported": ["Claim here"]
    }}
  ]
}}
"""

    return ask_openai_json(prompt, model=model, temperature=0.1)

from typing import Dict, Any, List


def embed_canonical_claims(
    verified_claims: Dict[str, Any],
    model: str = "text-embedding-3-small"
) -> Dict[str, Any]:
    """
    Convert each canonical_claim into an embedding vector.

    Input:
        verified_claims = {
            "verified_claims": [
                {
                    "canonical_claim": "...",
                    "trust_label": "high",
                    "weighted_support_score": 5.2,
                    ...
                }
            ]
        }

    Output:
        Same structure, but each claim now has an "embedding" field.
    """

    embedded_claims = []

    for item in verified_claims.get("verified_claims", []):
        claim_text = item.get("canonical_claim", "")

        if not claim_text:
            continue

        response = openai_client.embeddings.create(
            model=model,
            input=claim_text
        )

        vector = response.data[0].embedding

        embedded_item = {
            **item,
            "embedding_model": model,
            "embedding": vector
        }

        embedded_claims.append(embedded_item)

    return {
        "verified_claims": embedded_claims
    }

# ---------------------------------------------------------
# Main function
# ---------------------------------------------------------

def build_canonical_topic_json_v2(
    topic: str,
    output_path: str = "canonical_document_v2.json",
    min_subtopics: int = 4,
    max_subtopics: int = 10,
    min_sources_per_subtopic: int = 3
) -> Dict[str, Any]:

    subtopics = generate_subtopics(
        topic=topic,
        min_subtopics=min_subtopics,
        max_subtopics=max_subtopics
    )

    all_subtopic_outputs = []
    all_claims = []

    for subtopic in subtopics:
        print(f"Processing subtopic: {subtopic}")

        sources = search_with_fallback(
            topic=topic,
            subtopic=subtopic,
            min_sources=min_sources_per_subtopic
        )

        if not sources:
            all_subtopic_outputs.append({
                "subtopic": subtopic,
                "warning": "No quality sources found.",
                "claims": []
            })
            continue

        extracted = extract_claims_from_sources(
            topic=topic,
            subtopic=subtopic,
            sources=sources
        )

        extracted["sources_used"] = [
            {
                "source_id": source.get("source_id"),
                "title": source.get("title"),
                "url": source.get("url"),
                "domain": source.get("domain"),
                "source_quality_tier": source.get("source_quality_tier"),
                "source_weight": source.get("source_weight"),
            }
            for source in sources
        ]

        all_subtopic_outputs.append(extracted)

        for claim in extracted.get("claims", []):
            claim["subtopic"] = subtopic
            all_claims.append(claim)

    clustered = cluster_claims_strict(all_claims)

    verified = verify_clusters_weighted(clustered)

    embedded_verified = embed_canonical_claims(verified)

    document = write_canonical_document(
        topic=topic,
        subtopics=subtopics,
        verified_claims=verified,
        model="gpt-4.1"
    )

    document["metadata"] = {
        "created_at": datetime.utcnow().isoformat(),
        "topic": topic,
        "subtopics": subtopics,
        "pipeline_version": "v2_source_quality_weighted_trust",
        "notes": [
            "Sources filtered by quality tier before extraction.",
            "Duplicate domains and near-identical content removed before trust scoring.",
            "Trust labels use weighted source quality, not raw source count.",
            "Low-trust claims are forbidden from canonical prose."
        ]
    }

    document["intermediate"] = {
    "subtopic_extractions": all_subtopic_outputs,
    "clustered_claims": clustered,
    "verified_claims": verified,
    "embedded_verified_claims": embedded_verified
}
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(document, f, indent=2, ensure_ascii=False)

    return document

topic = "Chinese Economic Past, Present and Future"

document = build_canonical_topic_json_v2(
    topic=topic,
    output_path="quantum_agentic_ai_canonical_v2.json",
    min_subtopics=1,
    max_subtopics=2,
    min_sources_per_subtopic=3
)

print(json.dumps(document, indent=2, ensure_ascii=False))

print(json.dumps(document, indent=2, ensure_ascii=False))

embedded_verified

